apiVersion: batch/v1
kind: Job
metadata:
  name: parsec-vips
  labels:
    name: parsec-vips
spec:
  template:
    spec:
      containers:
      - image: anakli/cca:parsec_vips
        name: parsec-vips
        imagePullPolicy: Always
        resources: 
          requests: 
            cpu: "3.5"
          limits: 
            cpu: "4.0"
        command: ["/bin/sh"]
        args: ["-c", "taskset -c 0-3 ./run -a run -S parsec -p vips -i native -n 8"]
      restartPolicy: Never
      nodeSelector:
        cca-project-nodetype: "node-b-4core"
