apiVersion: batch/v1
kind: Job
metadata:
  name: parsec-ferret
  labels:
    name: parsec-ferret
spec:
  template:
    spec:
      containers:
      - image: anakli/cca:parsec_ferret
        name: parsec-ferret
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: "1.6"
            memory: "6Gi"
          limits:
            cpu: "4"
            memory: "8Gi"
        command: ["/bin/sh"]
        args: ["-c", "./run -a run -S parsec -p ferret -i native -n 4"]
      restartPolicy: Never
      nodeSelector:
        cca-project-nodetype: "node-b-4core"
